pipeline:
  properties:
    ci:
      codebase:
        connectorRef: account.diegogithubapp
        repoName: harness-react-native
        build: <+input>
  stages:
    - stage:
        name: Build and Deploy
        identifier: Build_and_Deploy
        template:
          templateRef: account.CICDREACTNATIVE
          versionLabel: 0.0.1
  name: MOBILE-IOS-REACT-NATIVE
  identifier: MOBILEIOSREACTNATIVE
  tags: {}
  projectIdentifier: DevOps_Experience
  orgIdentifier: SE_Sandbox
