pipeline:
  name: Python Utils Build
  identifier: Python_Utils_Build
  projectIdentifier: DevOps_Experience
  orgIdentifier: SE_Sandbox
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: account.diegogithubapp
        repoName: python-utils
        build: <+input>
  stages:
    - stage:
        name: Build Image
        identifier: Build_Image
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: BuildAndPushDockerRegistry
                  name: BuildAndPushDockerRegistry
                  identifier: BuildAndPushDockerRegistry
                  spec:
                    connectorRef: account.DockerHubDiego
                    repo: diegokoala/python-utils
                    tags:
                      - latest
